language: go
go:
- 1.8.x
services:
- docker
sudo: false
script:
- go get -t -v ./...
- make
notifications:
  slack:
    secure: w6YKgpDyBy3STg4tCehdViEeXMC3ODddIHFXaX7uQEDa0ZDqllzmpFU/p0IRLGDrJE6rEJoTeYCgCAgKMqJBVTgvgDqaHKskSJ4i0cqJTU+543V7zt/QKJJxJWcOC4r7o+b5aSZKot7nA/sjNDUstNhDBzRvCPUtnu6ZBQDE5IXouYEp6Xes4AJvu/hyYtggOkqWvW8/EKylwfRCnsgJtaZ9UF3iFV2KY1GMOzUTNGdVkVBfhajOTG9Bta2+qq1Sgwz6pzANHeW4bxhDEdvhO9fkBeNN15ZScEyfnT+0hIicTZ9HaBpwF4H9Xv4kE6QKTocksPWsCmF8njG3GQgRJq8vuKu1+Vcx8etiRjQKl6rwG6oC43zM31XV9OhWPjvpRO0NVRJkNl10z/LNvMr++H1pr9uniXTQD0pASAMCu3A//cE/b7qWKPSIqPmOsvCsVzznaIc/ao/GUNEx60G+J4ivKJOFo0kzBg+0Ulp+GCE2c3Vjudh3Jm7J0kzxsCPpPIOh/PeBAq1ktjmu6A4XJ41VDwIMEGA7oXJJvTiFIZ8VfHcI1mezpGwRgn5CBSQxw9BGHHwSLG0Cdecbo5CjAEOL2UNAgU0xoIAHC9iOnZwe2uBVHjouZC6YUT0xudBaarrHc9flQTbNkDoCVFRBp56h7jKhR6Xos6Z7g/VJMeI=
  hipchat:
    rooms:
      secure: e/y+jizCvdEDMgqBDBdwxvx3EFV/OoDyj6EOk3ppdkbqECPItz1fUow1iiyh7oyot/NpNWZSugne41nfB+NmSiEyePbIv/njsEh3mqLZ1HDnDzsLdtoJyaq7VjF6TqYDprPvi6QAlfebXqWiPo3HEFeqxdBdm3zTS0u+ozjcw3MSo2GX7eIm/dcx4RLWPVxQYKxhjAmH59ePb0DGgc1uK4PFSihElQuhstvSVmxHuB/mWONsrzKgd2ZwZSXpgaF1BoR5x9xHcl5EbiuCrIYwI4PPdgqQVnlCXkex0lqeFh4qe3tj43Fzz0nXxEo4uAsbNg+r06dz9wOCrioJzx3hJ4sb03o+4SJyBvRvNV8AsIeFm+K5AIjfhjmnsO2ZIl9NvaANYJ4pEHPn3ZybsCWPP7Gf6REnmSd172XtB/LmiKuWlVTK0pXboZL4zcGNVeewkF4oSGQfqeDycGUMqspblbEzEuo7fLb/s+KDfQ7oSb48BFAgXGlOvaQJYTIViPcJe8JWxRs8Pj/J1CBeZM0dcFhbrruYJKHfonv3Sjxy1HWMYDCs1ANJmaV/V4yQfPSU/2N9UXfKK4UJaKayXuqWC/jxvH2h3oOH/+UqW1eoCbWq7cHeXmQ4eU0MUzouOM2AwSpR+OU704Pe4t5xGlNekce3kBkIy8SfzJuRxEkLEX0=
