language: go
go:
- 1.8.x
services:
- docker
sudo: false
script:
- go get -t -v ./...
- make
notifications:
  slack:
    secure: w6YKgpDyBy3STg4tCehdViEeXMC3ODddIHFXaX7uQEDa0ZDqllzmpFU/p0IRLGDrJE6rEJoTeYCgCAgKMqJBVTgvgDqaHKskSJ4i0cqJTU+543V7zt/QKJJxJWcOC4r7o+b5aSZKot7nA/sjNDUstNhDBzRvCPUtnu6ZBQDE5IXouYEp6Xes4AJvu/hyYtggOkqWvW8/EKylwfRCnsgJtaZ9UF3iFV2KY1GMOzUTNGdVkVBfhajOTG9Bta2+qq1Sgwz6pzANHeW4bxhDEdvhO9fkBeNN15ZScEyfnT+0hIicTZ9HaBpwF4H9Xv4kE6QKTocksPWsCmF8njG3GQgRJq8vuKu1+Vcx8etiRjQKl6rwG6oC43zM31XV9OhWPjvpRO0NVRJkNl10z/LNvMr++H1pr9uniXTQD0pASAMCu3A//cE/b7qWKPSIqPmOsvCsVzznaIc/ao/GUNEx60G+J4ivKJOFo0kzBg+0Ulp+GCE2c3Vjudh3Jm7J0kzxsCPpPIOh/PeBAq1ktjmu6A4XJ41VDwIMEGA7oXJJvTiFIZ8VfHcI1mezpGwRgn5CBSQxw9BGHHwSLG0Cdecbo5CjAEOL2UNAgU0xoIAHC9iOnZwe2uBVHjouZC6YUT0xudBaarrHc9flQTbNkDoCVFRBp56h7jKhR6Xos6Z7g/VJMeI=
  hipchat:
    rooms:
      secure: P5oy/sf3dJWesA5EWLiRrHtRpIzxgnM0rqkX5XEbYn4AEtNRAXpe72B8LjsZqYBWln17PrVNTS5fOahvY8OcnaGm8vK0TZC/6cVGU3b0VPlk0b2Pt6lCB+s/irwBWOfQX74h1W+M6AoSV6zUsHewUzt+kz9eh9P74+wOSjIdGKD04BdLgM8QVzIOJLTKiNStZRUCMEaHMikAdaGiEdUXclf/wkrAqHLYkCP+gOWrM5eYo9/RCXjoYQapU87ksFIP0ho6MmFMczbqt1dc183ojuzlPlc1P8XZf6Cie9Do4MZrGGS2Bty5/uUCv0ep8XnL/ZjgBsNVKwnrYEdrP5aVRazlw3f+DUK1ZbrLW7c0iaA5T33x80BZnadtQz8h39oqf0xn1Ly3sY12SG/XOshPba5o+j7IdmdA4e1h9GmyQ0UKHgyHV5cP6hEa2ezwN88arYleG7UPWVuDwBkxMRaszNv75HbvpNzN6Zysy5E9U1w5cz48R+sY1x74ApjrqfIQ2r9E5QonnLJEo7G50N9B/CRyGFq9S28fzEdA2iB62JIx7j+7KI2Dp3z9Md9FV3jbIWzp3WLDZjLONPMVYl8lnMPou5n0NhamdYF4aDiU92g7nyQG+Pf/9WXaf7cz9O8rVQ2/0yqt9/qgspcIwc/Xcik1iCPsEmfOEWhRsFOa9nU=
