language: go
go:
- 1.8.x
services:
- docker

sudo: false
before_script:
  - go vet ./...
install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

  
notifications:
  slack:
    secure: w6YKgpDyBy3STg4tCehdViEeXMC3ODddIHFXaX7uQEDa0ZDqllzmpFU/p0IRLGDrJE6rEJoTeYCgCAgKMqJBVTgvgDqaHKskSJ4i0cqJTU+543V7zt/QKJJxJWcOC4r7o+b5aSZKot7nA/sjNDUstNhDBzRvCPUtnu6ZBQDE5IXouYEp6Xes4AJvu/hyYtggOkqWvW8/EKylwfRCnsgJtaZ9UF3iFV2KY1GMOzUTNGdVkVBfhajOTG9Bta2+qq1Sgwz6pzANHeW4bxhDEdvhO9fkBeNN15ZScEyfnT+0hIicTZ9HaBpwF4H9Xv4kE6QKTocksPWsCmF8njG3GQgRJq8vuKu1+Vcx8etiRjQKl6rwG6oC43zM31XV9OhWPjvpRO0NVRJkNl10z/LNvMr++H1pr9uniXTQD0pASAMCu3A//cE/b7qWKPSIqPmOsvCsVzznaIc/ao/GUNEx60G+J4ivKJOFo0kzBg+0Ulp+GCE2c3Vjudh3Jm7J0kzxsCPpPIOh/PeBAq1ktjmu6A4XJ41VDwIMEGA7oXJJvTiFIZ8VfHcI1mezpGwRgn5CBSQxw9BGHHwSLG0Cdecbo5CjAEOL2UNAgU0xoIAHC9iOnZwe2uBVHjouZC6YUT0xudBaarrHc9flQTbNkDoCVFRBp56h7jKhR6Xos6Z7g/VJMeI=
